version: "3"
services:
  php5.6:
    image: daishun/php:5.6-fpm
    volumes:
      - ../:/app
      - ~/.composer-docker/cache:/root/.composer/cache
    env_file:
      - ./php5.6/.env
    extra_hosts:
      - "api.host.com:10.8.40.112"
      - "api.matcher.com:10.8.40.112"
      - "lm-mock.dev.com:10.8.40.112"
      - "hf.dev.com:10.8.40.112"

  php7.1:
    image: daishun/php:7.1-fpm
    volumes:
      - ../:/app
      - ~/.composer-docker/cache:/root/.composer/cache
    env_file:
      - ./php7.1/.env
    extra_hosts:
      - "api.host.com:10.8.40.112"
      - "api.matcher.com:10.8.40.112"
      - "lm-mock.dev.com:10.8.40.112"
      - "hf.dev.com:10.8.40.112"

  nginx:
    image: nginx:1.12-alpine
    ports:
      - 80:80
    volumes:
      - ../:/app
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php5.6
      - php7.1
    extra_hosts:
      - "lm-mock.dev.com:127.0.0.1"

